# Generated by Django 4.0 on 2021-12-23 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('sportswear', 'Sportswear'), ('officewear', 'Officewear'), ('casualWear', 'Casualwear'), ('summerwear', 'Summerwear'), ('winterwear', 'Winterwear'), ('beachwear', 'Beachwear')], default='casualWear', max_length=100)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
